if [[ ! `uname` == *"Darwin"* ]]; then
    alias open='xdg-open'
fi
alias vim='nvim'
alias python='python3'
alias pip='pip3'
alias la='ls -aF'
alias ll='ls -alF'
alias gap='git add -p'
alias gs='git status'
alias gd='git diff'
alias yers='yes'
alias trustmebro='sudo'
alias update='echo -e "\n\neos-update --aur...\n\n" && yes | eos-update --aur && echo -e "\n\nUpdating pacman...\n\n" && yes | sudo pacman -Syu'
alias cdscylla='cd ~/Nextcloud/misc/KeyboardMappings/qmk_userspace/keyboards/'
alias escylla='cdscylla && vim bastardkb/scylla/keymaps/my_keymap/keymap.c'
alias fscylla='cdscylla && qmk compile -c -kb bastardkb/scylla/ -km my_keymap && qmk flash -kb bastardkb/scylla/ -km my_keymap'

if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto -F'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
alias cdds='cd ~/.local/share/Steam/steamapps/compatdata/570940/pfx/drive_c/users/steamuser/Documents/NBGI/DARK\ SOULS\ REMASTERED/76943598/'
alias cdlies='cd ~/.local/share/Steam/steamapps/common/Lies\ of\ P/LiesofP/Saved/SaveGames/76943598'
