# ~/.bashrc
#
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias open='xdg-open'
alias la='ls -a'
alias ll='ls -l'
alias smake='make -j$(shell grep -c ^processor /proc/cpuinfo);'

source ~/.bash_prompt

set -o vi
