source ~/.bash_prompt

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

uname='uname'
if [[ "$uname" == 'Linux' ]]; then
    . /etc/profile.d/vte.sh
    alias open='xdg-open'
fi
if [ -f `brew --prefix`/etc/bash_completion ]; then
    . `brew --prefix`/etc/bash_completion
fi


alias la='ls -a'
alias ll='ls -l'

set -o vi
