"Leader mappings
let mapleader=","
let maplocalleader=","
nmap \ <Leader><Leader>

if &compatible
    set nocompatible
endif

"Use semicolon to enter commands
nnoremap ; :

"Disable EX mode
noremap Q <NOP>

"Run pathogen
filetype plugin indent on
execute pathogen#infect()

"include .tags
set tags=./.tags;/

"Make views automatic
autocmd BufWinEnter * silent loadview
autocmd BufWinLeave * mkview

"Automatically remove trailing whitespace
autocmd BufWinEnter * %s/\s\+$//e
autocmd BufWritePre * %s/\s\+$//e

"Keep persistent undo trees
if has('persistent_undo')
    set undodir=$HOME/.vim/vimundo
    set undofile
endif

"Number lines
set relativenumber
"Leave 3 lines above, below cursor
set scrolloff=3

"Show line, column number
set ruler
"Always show status line
set laststatus=2
"Show tab line when 2 or more tabs are open
set showtabline=1
"Don't show "@" symbols when lines don't fit
set display+=lastline

"Make sure backspace works like you'd expect
set backspace=indent,eol,start

"Tab formatting
"4 spaces per tab
set softtabstop=4
"4 spaces when indenting
set shiftwidth=4 tabstop=4 expandtab
"Smart indenting stuff
set autoindent smartindent

"Highlight characters that exit in column 81.
call matchadd('ColorColumn','\%81v',255)

"A few misc things
syntax on
set smartcase ignorecase showmatch incsearch hlsearch wildignorecase wildmenu

"Keep current buffer at the top for sp, left for vsp
set splitbelow splitright

"Let tab, shift+tab indent and unindent
nnoremap <silent> <TAB> :tabn<Cr>
nnoremap <silent> <S-TAB> :tabp<Cr>

"Colorscheme
set background=dark t_Co=256
colorscheme molokai

"Automatically follow directory
" set autochdir

"Remove trailing whitespace
nnoremap <silent> <leader>W :%s/\s\+$//e <bar> nohlsearch<CR>

"Reformat current paragraph
"Use with caution
nnoremap <Leader>F gqip :%s/\s\+$//e <bar> nohlsearch <CR><C-o>

"Toggle Tab Highlighting
map <Leader>t :ToggleTabHi<CR>

"Toggle Trailing Whitespace Highlighting
map <Leader>w :ToggleSpaceHi<CR>

"Toggle spelling
nnoremap <Leader>s :set spell!<CR>

"Save and put vim in the background
nnoremap <leader>z :w<CR><C-z>

"Align in visual
vnoremap <Leader>te :Tab /=<CR>
vnoremap <Leader>tc :Tab /:<CR>

"Clear search highlight
nmap <Leader>/ :nohlsearch<CR>

"Toggle colorcolumn
nnoremap <Leader>c :exec 'set' (&colorcolumn ==# '') ? 'colorcolumn=+1' : 'colorcolumn='<CR>

"Easily switch sp to vsp
nnoremap <Leader>vs <C-w>t<C-w>K
"Easily switch vsp to sp
nnoremap <Leader>sv <C-w>t<C-w>H

"Disable help
noremap <F1> <NOP>
noremap! <F1> <NOP>

"Remap tab to change tab levels in visual mode
vnoremap <TAB> >
vnoremap <S-TAB> <

"Make text scolling constant
nnoremap j gj
nnoremap k gk
nnoremap gj j
nnoremap gk k

"Allow writing even if you forgot to sudo
cmap w!! w !sudo tee % >/dev/null
cmap x!! x !sudo tee % >/dev/null
